CREATE TABLE agents (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE commodities (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE inventories (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  agent_id INTEGER NOT NULL,
  commodity_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  max_quantity INTEGER NOT NULL
);

CREATE TABLE price_beliefs (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  agent_id INTEGER NOT NULL,
  commodity_id INTEGER NOT NULL,
  max_price FLOAT NOT NULL,
  min_price FLOAT NOT NULL,
  FOREIGN KEY (agent_id) REFERENCES Agents(id),
  FOREIGN KEY (commodity_id) REFERENCES Commodities(id)
);

CREATE TABLE offers (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  agent_id INTEGER NOT NULL,
  commodity_id INTEGER NOT NULL,
  is_buy BOOLEAN NOT NULL,
  price FLOAT NOT NULL,
  quantity INTEGER NOT NULL,
  FOREIGN KEY (agent_id) REFERENCES Agents(id),
  FOREIGN KEY (commodity_id) REFERENCES Commodities(id)
);

CREATE TABLE trades (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  buy_offer_id INTEGER NOT NULL,
  sell_offer_id INTEGER NOT NULL,
  commodity_id INTEGER NOT NULL,
  price FLOAT NOT NULL,
  quantity INTEGER NOT NULL,
  FOREIGN KEY (buy_offer_id) REFERENCES Offers(id),
  FOREIGN KEY (sell_offer_id) REFERENCES Offers(id)
)
